# Generated by Django 3.1.7 on 2021-05-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    def init_empty_DB_entry(apps, schema_editor):
        # Create an empty entry in Actor DB table.
        Actor = apps.get_model('core', 'Actor')
        Actor.objects.create(name='', kind='NUL', comment='Empty entry creating during init. DO NOT REMOVE')
        # Create an empty entry in Actor DB table.
        Area = apps.get_model('core', 'Area')
        Area.objects.create(name='', criticality='N', comment='Empty entry creating during init. DO NOT REMOVE')

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_empty_DB_entry)
    ]
