# Generated by Django 3.1.7 on 2021-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210518_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='core.actor'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='core.area'),
        ),
    ]
