# Generated by Django 3.1.7 on 2021-05-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrupted',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artifact'),
        ),
        migrations.AlterField(
            model_name='corrupted',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endpoint'),
        ),
    ]
