# Generated by Django 3.1.7 on 2021-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210518_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('IP', 'IP Address'), ('FQDN', 'Domain'), ('URL', 'URL path'), ('JA3', 'JA3/JA3S'), ('PROC', 'Process'), ('HIVE', 'Registry Key'), ('FILE', 'File or Folder'), ('HASH', 'HASH'), ('OTH', 'Other ...')], default='OTH', max_length=4),
        ),
    ]
