# Generated by Django 3.1.7 on 2021-05-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210518_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='lastName',
        ),
    ]
